LIB = ../../../lib

TEST_NAME = test_text_pointer

INC += $(LIB)/hw/include

INC += $(LIB)/emu/graphic
INC += $(LIB)/graphic
INC += $(LIB)/graphic/fonts
INC += $(LIB)/graphic/text
SRC += $(LIB)/graphic/text/text_pointer.c

include $(LIB)/emu/emu_dp_dep.mk
include $(LIB)/emu/test_console.mk
