PROJECT = ../../..
LIB = $(PROJECT)/../../lib


# INC += $(PROJECT)/widgets
# SRC += $(PROJECT)/widgets/*.c

# INC += ./$(LIB)/hw/include/

INC += ./
SRC += ./*.c

INC += ./$(LIB)/../tests/ui_layout
SRC += ./$(LIB)/../tests/ui_layout/widget_test_rect_with_text.c

# SRC += ./$(LIB)/emu/hw/systick.c

# INC += $(PROJECT)/logic
# SRC += $(PROJECT)/logic/metrics_view.c
# SRC += $(PROJECT)/logic/metrics_ecu.c
# SRC += $(PROJECT)/logic/trip_integrate.c


screen_switch_test_run:

include $(LIB)/emu/test_graphic_color.mk
