LIB = ../../../lib

# fonts.h
INC += $(LIB)/graphic/fonts
SRC += $(LIB)/graphic/fonts/*.c

# lcd_text_color.h
INC += $(LIB)/graphic/lcd_color
SRC += $(LIB)/graphic/lcd_color/*.c

# misc.h
INC += $(LIB)/common

lcd_text_color_print_test_run:

include $(LIB)/emu/graphic/emu_graphic.mk
