LIB = ../../lib

all: storage_test_test_run

INC += $(LIB)/storage
INC += $(LIB)/hw/include
INC += $(LIB)/common

SRC += $(LIB)/storage/storage.c
SRC += $(LIB)/emu/storage/emu_flash.c

include $(LIB)/emu/test_console.mk
