LIB = ../../../lib

test_debug_print_run:

INC += $(LIB)/common
SRC += $(LIB)/common/str_val.c
SRC += $(LIB)/common/str_val_buf.c
SRC += $(LIB)/common/str_utils.c

SRC += $(LIB)/emu/console/emu_dp_usart.c

include $(LIB)/emu/test_console.mk
