LIB = ../../../lib

SRC += second_module_dp.c

INC += $(LIB)/common
SRC += $(LIB)/common/str_val.c
SRC += $(LIB)/common/str_val_buf.c
SRC += $(LIB)/common/str_utils.c

SRC += $(LIB)/emu/console/emu_dp_usart.c

TEST_NAME = test_debug_print

include $(LIB)/emu/test_console.mk
