LIB = ../../../lib

INC += $(LIB)/hw/include
INC += $(LIB)/common

SRC += $(LIB)/common/tasks.c
SRC += $(LIB)/common/str_utils.c
SRC += $(LIB)/common/str_val.c
SRC += $(LIB)/common/str_val_buf.c

TEST_NAME = test_tasks

include $(LIB)/emu/test_console.mk
