LIB = ../../../lib
TEST_NAME = test_tasks

INC += $(LIB)/hw/include
SRC += $(LIB)/common/tasks.c
SRC += $(LIB)/common/ll.c
SRC += $(LIB)/common/eq.c

include $(LIB)/emu/emu_dp_dep.mk
include $(LIB)/emu/test_console.mk
