UCLIB_PATH = ../..

LIB = $(UCLIB_PATH)/lib

INC += $(LIB)/common
INC += $(LIB)/graphic/fonts

SRC += $(LIB)/graphic/fonts/*.c
SRC += $(LIB)/common/*.c

INC += ./
SRC += ./*.c

INC += $(UCLIB_PATH)/lib/graphic/ui_tree
SRC += $(UCLIB_PATH)/lib/graphic/ui_tree/*.c

INC += $(UCLIB_PATH)/tests/

include $(UCLIB_PATH)/emu/emu.mk
