LIB = ../../../lib

# array_size.h
INC += $(LIB)/common

# coord_type.h
INC += $(LIB)/emu/graphic

# forms.h
INC += $(LIB)/graphic

# forms_align.h
INC += $(LIB)/graphic/forms
SRC += $(LIB)/graphic/forms/forms_align.c

test_forms_align_run:

include $(LIB)/emu/test_console.mk
