
LIB = ../../../lib

# widget_test_rect_with_text.h
INC += $(LIB)/graphic/ui_tree/widgets
SRC += $(LIB)/graphic/ui_tree/widgets/widget_test_rect_with_text.c
SRC += $(LIB)/graphic/ui_tree/widgets/widget_layout_tree.c

main: ui_layout_test_run

include $(LIB)/emu/graphic/emu_graphic_ui_tree.mk

