LIB = ../../../../../lib

INC += ../../../logic
INC += $(LIB)/common

SRC += ../../../logic/metrics_ecu.c
SRC += $(LIB)/common/str_utils.c

TEST_NAME = test_metrics_ecu_calc

include $(LIB)/emu/test_console.mk
