LIB = ../../../lib

# fonts.h
INC += $(LIB)/graphic/fonts
SRC += $(LIB)/graphic/fonts/*.c

# lcd_text_color.h
INC += $(LIB)/graphic/lcd_color
SRC += $(LIB)/graphic/lcd_color/print_char.c

# misc.h
INC += $(LIB)/common

INC += $(LIB)/graphic/forms
SRC += $(LIB)/graphic/forms/*.c

INC += $(LIB)/graphic/text
SRC += $(LIB)/graphic/text/text_pointer.c
SRC += $(LIB)/graphic/text/font_config.c
SRC += $(LIB)/graphic/text/text_print.c

TEST_NAME = test_lcd_color_tptr_print

include $(LIB)/emu/graphic/emu_graphic.mk
