#pragma once

enum {
    EVENT_NONE = 0,
    EVENT_BTN_LEFT,
    EVENT_BTN_RIGHT,
    EVENT_BTN_UP,
    EVENT_BTN_DOWN,
    EVENT_BTN_OK,


    EVENT_LONG_BTN_LEFT,
    EVENT_LONG_BTN_RIGHT,
    EVENT_LONG_BTN_UP,
    EVENT_LONG_BTN_DOWN,
    EVENT_LONG_BTN_OK,

    EVENT_BTN_BACK = EVENT_BTN_LEFT,
    EVENT_BTN_MODE = EVENT_BTN_RIGHT,
};
