LIB = ../../../lib

INC += $(LIB)/common

SRC += $(LIB)/common/val_text.c
SRC += $(LIB)/common/str_val.c
SRC += $(LIB)/common/str_utils.c

TEST_NAME = test_val_text

include $(LIB)/emu/test_console.mk
