LIB = ../../../../../lib

all: metrics_calc_test_run

INC += ../../../logic
INC += $(LIB)/common

SRC += ../../../logic/metrics_view.c
SRC += $(LIB)/common/str_utils.c

include $(LIB)/emu/test_console.mk
