LIB = ../../../lib

# fonts.h
INC += $(LIB)/graphic/fonts
SRC += $(LIB)/graphic/fonts/*.c

# lcd_text_color.h
INC += $(LIB)/graphic/lcd_color
SRC += $(LIB)/graphic/lcd_color/*.c

# misc.h
INC += $(LIB)/common

TEST_NAME = test_lcd_color_text_raw_print

include $(LIB)/emu/graphic/emu_graphic.mk
