LIB = ../../../lib

# fonts.h
INC += $(LIB)/graphic/fonts
SRC += $(LIB)/graphic/fonts/*.c

# lcd_text_color.h
INC += $(LIB)/graphic/lcd_color
SRC += $(LIB)/graphic/lcd_color/*.c

# misc.h
INC += $(LIB)/common

#------------------------------------------------------------

# ui_tree.h
INC += $(LIB)/graphic/ui_tree
SRC += $(LIB)/graphic/ui_tree/ui_tree.c

# debug_print.h
INC += $(LIB)/emu

# widget_test_rect_with_text.h
INC += $(LIB)/emu/graphic/widgets
SRC += $(LIB)/emu/graphic/widgets/widget_test_rect_with_text.c

SRC += $(LIB)/graphic/lcd_text.c
SRC += $(LIB)/common/str_utils.c
SRC += $(LIB)/graphic/align_forms.c

ui_tree_text_form_test_run:

include $(LIB)/emu/graphic/emu_graphic.mk
