LIB = ../../../lib

# widget_test_rect_with_text.h
INC += $(LIB)/graphic/ui_tree/widgets
SRC += $(LIB)/graphic/ui_tree/widgets/widget_test_rect_with_text.c

ui_tree_text_form_test_run:

include $(LIB)/emu/graphic/emu_graphic_ui_tree.mk
