LIB = ../../lib

INC += $(LIB)/graphic/ui_tree/
SRC += $(LIB)/graphic/ui_tree/ui_tree.c

INC += $(LIB)/graphic/
SRC += $(LIB)/graphic/forms.c

INC += $(LIB)/emu/
INC += $(LIB)/common/

all: ui_tree_element_delete_test_run

include $(LIB)/emu/test_console.mk
