LIB = ../../lib

INC += $(LIB)/graphic/ui_tree/
SRC += $(LIB)/graphic/ui_tree/ui_tree.c

INC += $(LIB)/../forms/
SRC += $(LIB)/../forms/forms.c

INC += $(LIB)/../emu/
INC += ../

INC += $(LIB)/common/

all: ui_tree_element_delete_test_run

include ../test_console.mk
