PROJECT = ../../..

# widgets
INC += $(PROJECT)/widgets
INC += $(PROJECT)/widgets/common

SRC += $(PROJECT)/widgets/common/widget_selectable_list.c
SRC += $(PROJECT)/widgets/common/widget_text.c

# str_val.h
INC += $(LIB)/common/
SRC += $(LIB)/common/str_val.c

TEST_NAME = selectable_list

include ../emu_widget.mk
